
##from keyboard import mouse
import keyboard
import time

key = ''
########################### Ingrese Clave para Iniciar ################################################################		
while key != '1409':
	key = input("Introduzca Contraseña:  ")

########################### Fin Ingrese Clave para Iniciar ############################################################


########################### Colocar Canción Fantasia   ################################################################
print("\n")
print("Hola amor, Feliz primer Año para nosotros \n")
time.sleep(2)
print("Ahora yo tengo el control de tu Pc por un ratito, no te asustes es normal, no toques nada y deja que fluya\n")
time.sleep(3)
keyboard.send('windows')
time.sleep(2)
keyboard.write('Google Chrome')
keyboard.send('enter')
time.sleep(3)
keyboard.write('https://www.youtube.com/watch?v=7BinD8qJjqM')
keyboard.send('enter')
time.sleep(3)


########################### Fin Colocar Canción Fantasia   #############################################################

########################### Nota de Amor, calcular cancion Dura 203 Segundos ###########################################
keyboard.send('alt+tab')

print("Por lo general, yo no suelo llevar la cuenta de cuanto llevamos juntos\n")
time.sleep(2)
print("Pero, por la persona correcta se logran hacer grandes cambios\n")
time.sleep(2)
print("Este ha sido un año con muchas emociones\n")
time.sleep(2)
print("Hemos tenido muy lindos momentos, pero tambien unos muy fuertes\n")
time.sleep(2)
print("Y a pesar de todo eso, aqui estamos!!\n")
time.sleep(2)
print("Luchando, queriendonos, demostrandonos a nosotros mismos que sí lo podemos lograr\n")
time.sleep(2)
print("Que la distancia y los miedos son grandes enemigos\n")
time.sleep(2)
print("Pero no hay nada que el Team OriCar no pueda solucionar\n")
time.sleep(2)
print("Al principio creiamos que la edad iba a ser un problema\n")
time.sleep(2)
print("Luego fue la distancia\n")
time.sleep(2)
print("Una Distancia que disminuimos durante cortos lapsos de tiempo\n")
time.sleep(2)
print("Una y otra vez la vida se encargaba de separarnos físicamente\n")
time.sleep(2)
print("Pues, es lo único que podía hacer, ya que sentimentalmente era imposible\n")
time.sleep(2)
print("Pero, aun así lo intento y fueron todos esos momentos de bajas que hemos tenido\n")
time.sleep(2)
print("Pero ambos nos hemos resistido a darnos por vencidos\n")
time.sleep(2)
print("Antes de ti\n")
time.sleep(2)
print("De nada me espero, imagina de mi, me dijero ve a por todas ...\n")
time.sleep(2)
print("Y si Oriel, definitivamente    fui por TI\n")
time.sleep(2)
print("Y es que hay un dicho muy importante, que lo oí hace poco y me gusto bastante\n")
time.sleep(2)
print("Donde fuiste tan feliz, siempre regresaras\n")
time.sleep(2)
print("Y regreso a ti, no porque mi felicidad de ti dependa, sino porque contigo todo es mejor\n")
time.sleep(2)
print("Gran parte de eso es gracias a que hay tantos con quien estar, pero pocos con quien ser\n")
time.sleep(2)
print("Contigo no tengo que ser nadie mas, solo Carlos Sanguña, el real, el que no necesita colocar barreras\n")
time.sleep(2)
print("Tú, Oriel Hernández Vera, me dejas ser quien soy, no me juzgas, sino todo lo contrario, me aceptas\n")
time.sleep(2)
print("Aceptas cada locura mía, mi obsesión por el fútbol y sobretodo mi manera extraña de amarte \n")
time.sleep(2)
print("Algo gracioso, justo ahora te acabo de enviar un mensaje dice ''Estoy enamorado'' junto con una franela del Chelsea \n")
time.sleep(2)
print("Te dije que no te pusieras celosa y me dices 'Aprendí a no luchar contra tu pasión' \n")
time.sleep(2)
print("Entiendes por qué digo que contigo puedo ser quien realmente soy??\n")
time.sleep(2)
print("Se que no todo el mundo aguantaría cada estupidez y locura que hago, como tu lo aguantas\n")
time.sleep(2)
print("Poco a poco me daba cuenta de que el futuro no era lo que estaba adelante\n")
time.sleep(2)
print("Ahora si me doy cuenta de que era estar contigo\n")
time.sleep(2)
print("Y no por nada interesado, sino porque realmente en este mas de un año, me he demostrado que puedo formar parte de un gran equipo\n")
time.sleep(2)
print("Un equipo donde no hay un superior, sino donde ambos somos igual de importantes\n")
time.sleep(2)
print("Oriel tu me has enseñado lo bonito que es tener una pareja en el momento que yo mas le huia\n")
time.sleep(2)
print("'Como tu mano y mi mano en la noche no sienten frío, sin ti las horas se pasan pero con días vacíos'\n")
time.sleep(2)
print("Vacíos pero que cada vez recortaban mas el tiempo que nos quedaba separados\n")
time.sleep(2)
print("Y te entiendo perfectamente, se que mueres de miedo por toda esta aventura que ya comenzamos juntos pero que dara una gran paso ahora\n")
time.sleep(2)
print("Cuando no sepas a donde ir vete a donde de mas miedo\n")
time.sleep(2)
print("Es esos lugares donde amprendemos más de la vida \n")
time.sleep(2)
print("Y sobretodo donde muchas veces nos damos cuenta que estaba la verdadera alegría \n")
time.sleep(2)
print("Teníamos miedo de esta relación a distancia y ¿Quién lo diria?\n")
time.sleep(2)
print("Hemos pasado un gran noviazgo juntos\n")
time.sleep(2)
print("Que, aunque yo ahorita este en otra parte, soy más feliz porque pude encontrarte\n")
time.sleep(2)
print("Pero aun mucho mas feliz porque dentro de poco esa otra parte desaparecerá \n")
time.sleep(2)
print("Oriel tu eres perfecta, con todos tus defectos y pecados ... y por eso\n")
time.sleep(2)
print("No pienso dar ni un paso atrás en el camino que me lleve hacia tus besos\n")
time.sleep(2)
print("Sin saberlo, pase la vida entera buscando lo que por fin he encontrado.\n")
time.sleep(2)
print("Conoces la canción... Serías la correcta y yo el equivocado\n")
time.sleep(2)
print("Así como esa canción quiero que bailemos el mundo juntos\n")
time.sleep(2)
print("Se me acaba de ocurrir una idea\n")
time.sleep(2)
print("En todos los lugares que conozcamos juntos tanto en chile como en el resto del planeta, bailaremos juntos una canción\n")
time.sleep(2)
print("Quiza en la plaza, en el cuarto del hotel, pero seguro en el hogar que juntos construiremos\n")
time.sleep(2)
print("Ojo, si quieres que sea en una plaza creo que deberás ayudarme con aprender a bailar jejeje :D\n")
time.sleep(2)
print("Como dicen por ahi, mi sentido del ritmo es nulo y tengo cero pies izquierdos, ya que alguien con al menos 2 podría hacerlo mejor\n")
time.sleep(2)
print("Pero lo que me falta en pies, me sobra en amor para ti, amor que lo podemos recompilar en la mejor coreografía de vida\n")
time.sleep(2)
print("Todo esto es logrado en nombre del amor\n")
time.sleep(2)
print("En nombre de todo lo que siento por ti \n")
time.sleep(2)
print("En nombre de todo lo que se que tu sientes por mi\n")
time.sleep(2)
print("En nombre de felicidad eu juntos nos espera Bella\n")
time.sleep(2)
print("La vida no tuvo mas opción que dejarnos cumplir esta meta\n")
time.sleep(2)
print("Que es ayudarnos mutuamente mediante el cariño a lograr nuestros sueños\n")
time.sleep(2)
print("Si tu caes yo caere contigo, y tambien me levante contigo\n")
time.sleep(2)
print("Aunque mejor dicho, si tu caes yo estare ahi para darte apoyo a seguir adelante\n")
time.sleep(2)
print("Ese mismo apoyo que tu me has dado a pesar de todo lo que hemos pasado\n")
time.sleep(2)
print("Que ahora pensadolo bien, si lo ponemos en una balanza, es mucho mas los momentos Lindos que los difíciles\n")
time.sleep(2)
print("Solo que al ser Humanos le damos mas importancia a lo malo que a lo bueno\n")
time.sleep(2)
print("Sin darnos cuenta que lo bueno es lo que mas tenemos en nuestras vidas\n")
time.sleep(2)
print("Pero como dicen por ahi, como sabemos lo que felicidad si nunca pasamos por malos momentos\n")
time.sleep(2)
print("Pero me gusta más, las cosas malas a veces pasa, las buenas ...\n")
time.sleep(2)
print("Cambiando un poco de tema\n")
time.sleep(2)
print("Espero que te gusten tus regalitos\n")
time.sleep(2)
print("Me siento un poco mal porque estuve buscando por 2 semanas un charm de infinito\n")
time.sleep(2)
print("Y aunque no pude conseguir uno que me gustara se que es una señal de que el indicado aun no ha salido\n")
time.sleep(2)
print("En cuanto a los chocolates me guardas uno ... jajajajajjaja\n")
time.sleep(2)
print("No vale, disfrutalos bella, asi como yo disfruto cada segundo que yo paso a tu lado\n")
time.sleep(2)
print("Confieso que queria mandar un gran ramo, pero creo que vale más algo que realmente puedas usar y sobretodo disfrutar\n")
time.sleep(2)
print("No se si creias que se me iba a olvidar de esta fecha, pero jamas olvidaria nada contigo\n")
time.sleep(2)
print("Por cierto, cuando es que es tu cumple años???\n")
time.sleep(2)
print("Jajajajaja, espero sacarte una linda sonrisa, no solo con el chiste\n")
time.sleep(2)
print("Sino con la vida que se que juntos construiremos\n")
time.sleep(2)
print("Porque no importa cuantos ladrillos son lance la vida\n")
time.sleep(2)
print("Tu y Yo\n")
time.sleep(2)
print("El Team OriCar\n")
time.sleep(2)
print("Los agarrara y contruira un gran castillo\n")
time.sleep(2)
print("Uno en el cual vivamos felices y donde Juan nuestro gran dinosaurio si pueda estar\n")
time.sleep(2)
print("Lo estamos logrando bella\n")
time.sleep(2)
print("Poco a poco le demostramos al mundo que lo imposible juntos lo hacemos posible\n")
time.sleep(2)
print("Un beso mi Princesa...\n")
time.sleep(2)
print("Te quiero, Te adoro y Te extraño porque nadie se compara a tí\n")
time.sleep(2)
print("Te voy amar solo durante...\n")
time.sleep(2)
print("Por Siempre o mejor dicho \n")
time.sleep(2)
print("Por INFINITO\n")
time.sleep(2)
########################### Fin Nota de Amor, ###########################################################################



#########################  Final ####################################################3
print("Tu Pc es tuya de nuevo, pero antes me voy recordando la mejor canción que me sé. Te Amo Oriel Hernandez Vera\n")
time.sleep(3)
keyboard.send('alt+tab')
time.sleep(3)
keyboard.send('F6')
time.sleep(3)
keyboard.write('https://www.youtube.com/watch?v=a7fzkqLozwA&list=PLbK5xnZKw_y6cQappUIMl7sa9TRFQynZW')
time.sleep(1)
keyboard.send('enter')
time.sleep(3)
keyboard.send('ctrl+t')
time.sleep(2)
keyboard.write('https://www.instagram.com/stories/highlights/18018480631199709/')
keyboard.send('enter')
time.sleep(82)
keyboard.send('F6')
time.sleep(1)
keyboard.write('https://www.instagram.com/stories/highlights/17873766790312426/')
keyboard.send('enter')
time.sleep(378)
keyboard.send('ctrl+w')

